package mchorse.bbs_mod.ai.cap;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * The capability table the AI copilot is allowed to see (copilot spec
 * sections 3 L0 / 10.2 / 10.9). Generated by {@link AiCapabilityScanner} from
 * the SAME registries the UI reads - never a hand written list, so new
 * content types become callable without touching AI code.
 *
 * <p>Every capability carries a tier, because "callable" is not "writable":
 * read-only executes directly, writable goes through the edit patch +
 * confirmation, dangerous demands a second confirmation with scope shown.</p>
 */
public class CapabilityManifest
{
    public enum Tier
    {
        READ_ONLY, WRITABLE, DANGEROUS
    }

    public static class FormCapability
    {
        public final String id;
        public final String source;
        public final Tier tier = Tier.WRITABLE;
        public final List<ValueInfo> values = new ArrayList<>();

        public FormCapability(String id, String source)
        {
            this.id = id;
            this.source = source;
        }
    }

    public static class ValueInfo
    {
        public final String name;
        public final String type;
        public final boolean numeric;
        public final boolean animatable;

        public ValueInfo(String name, String type, boolean numeric, boolean animatable)
        {
            this.name = name;
            this.type = type;
            this.numeric = numeric;
            this.animatable = animatable;
        }
    }

    public static class KeyframeCapability
    {
        public final String type;
        public final boolean numeric;

        public KeyframeCapability(String type, boolean numeric)
        {
            this.type = type;
            this.numeric = numeric;
        }
    }

    /** form id -> capability; insertion order = registry order. */
    public final Map<String, FormCapability> forms = new LinkedHashMap<>();

    /** Registered keyframe factory types and whether they can take curves. */
    public final List<KeyframeCapability> keyframes = new ArrayList<>();

    /** Track kinds present in this build (TrackKind keys). */
    public final List<String> tracks = new ArrayList<>();

    /** Importer names (client filled). */
    public final List<String> importers = new ArrayList<>();

    /** Addon-declared skills, by id. */
    public final List<String> skills = new ArrayList<>();

    public FormCapability form(String id)
    {
        return this.forms.get(id);
    }
}
